# Copyright 2021 Triggermesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggermesh-routing-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      flow.triggermesh.io/routing-controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggermesh-routing-core
  labels:
    flow.triggermesh.io/routing-controller: "true"
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - events
    verbs: 
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs: 
    - get
    - list
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources: 
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - validatingwebhookconfigurations
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
  - apiGroups:
    - flow.triggermesh.io
    resources:
    - filters
    - filters/status
    - splitters
    - splitters/status
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - patch
    - watch
  # Manage receive-adapters
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
  - apiGroups:
    - serving.knative.dev
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
  # Manage resource-specific ServiceAccounts and RoleBindings
  - apiGroups:
    - ''
    resources:
    - serviceaccounts
    verbs:
    - list
    - watch
    - create
  - apiGroups:
    - ''
    resources:
    - serviceaccounts
    resourceNames:
    - filter-adapter
    - splitter-adapter
    verbs:
    - update
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    verbs:
    - list
    - watch
    - create
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    resourceNames:
    - filter-adapter
    - splitter-adapter
    verbs:
    - update
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filter-adapter
rules:
  - apiGroups: 
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - flow.triggermesh.io
    resources:
    - filters
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources: 
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splitter-adapter
rules:
  - apiGroups: 
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - flow.triggermesh.io
    resources:
    - splitters
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources: 
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
---
# Use this aggregated ClusterRole when you need readonly access to "Addressables"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addressable-resolver
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/addressable: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
# The role is needed for the aggregated role addressable-resolver in knative-eventing to provide readonly access to "Addressables".
# see https://github.com/knative/eventing/blob/release-0.16/docs/spec/channel.md#aggregated-addressable-resolver-clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routing-addressable-resolver
  labels:
    duck.knative.dev/addressable: "true"
rules:
- apiGroups:
  - flow.triggermesh.io
  resources:
  - filters
  - filters/status
  - splitters
  - splitters/status
  verbs:
  - get
  - list
  - watch
